### ISSUE TITLE
Suggestion: Plex

### ISSUE THREAD

**Issue by ppumkin** [rikai/jbdev#13]
You should seriously think about setting up a Plex channel/ Media Server.

One of the great features of Plex is the extremely powerful transcodders! (No, I tried to use plex for live re streaming, it kinda works but dont go there, yet.)

The nicest thing is that Plex app or website will detect what device you are on and it will recompress a master file into resolutions and bitrates that look good on the device without compromising quality "visible to the eyeball"

Also support saving to watch later. Its grown to similar to "iTunes" idea, but not crap. ie downlaod and watch later, but Plex will re encode the media to suit your device, iPhone, Nexus 7 or any 10" generic Android table, 55" TV. It will know how to deliver it to you. 

Also they are working on variable streaming rates, like Google, to prevent buffering on 3G, it will adjust the bitrate as bandwidth fluctuates."BETA"

**Comment by cbojar** [comment]
A member of our community has actually created a Plex plugin! It is open source (see: [LeonB/JupiterBroadcasting.bundle](https://github.com/LeonB/JupiterBroadcasting.bundle) and [plexinc-plugins/JupiterBroadcasting.bundle](https://github.com/plexinc-plugins/JupiterBroadcasting.bundle)) so you can feel free to contribute. It is also available from the Plex Channels directory for easy install.

**Comment by ppumkin** [comment]
Hi, after writting this I heard Chris mention that. But I actually didnt know about that either. So cool! 
:+1:
